language: node_js
node_js:
  - 13

services:
  - docker

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# Tasks to perform after the process is successful. Building docker images.
script:
  - docker --version # print the version for logging
  - docker build -t udagram-restapi-feed .
  - docker tag udagram-restapi-feed philchrist/udagram-restapi-feed:latest
  - docker build -t udagram-restapi-user .
  - docker tag udagram-restapi-user philchrist/udagram-restapi-user:latest
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend philchrist/udagram-frontend:latest
  - docker build -t udagram-reverseproxy .
  - docker tag udagram-reversepoxy philchrist/udagram-reversepoxy:latest
  - echo "done"


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push philchrist/udagram-restapi-feed
  - docker push philchrist/udagram-restapi-user
  - docker push philchrist/udagram-frontend
  - docker push philchrist/udagram-reversepoxy


