apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "html"
    port: 8100
    targetPort: 80
  selector:
    service: frontend
  type: LoadBalancer